apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: subatomic-repo
  description: an example of a repo
  tags:
    - jfrog
    - artifactory
spec:
  type: repo
  lifecycle: experimental
  owner: guest
